version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: react_app_container
    tty: true
    volumes:
      - ./node/react-sample:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
